echo "</select>" >> VG.html
echo "</select>" >> KY.html
echo "</select>" >> HR.html
echo "</select>" >> CW.html
echo "</select>" >> CZ.html
echo "</select>" >> DM.html
echo "</select>" >> DO.html
echo "</select>" >> EE.html
echo "</select>" >> HU.html
echo "</select>" >> ID.html
echo "</select>" >> JM.html
echo "</select>" >> LI.html
echo "</select>" >> MV.html
echo "</select>" >> MT.html
echo "</select>" >> MQ.html
echo "</select>" >> MC.html
echo "</select>" >> ME.html
echo "</select>" >> MS.html
echo "</select>" >> PH.html
echo "</select>" >> PL.html
echo "</select>" >> RO.html
echo "</select>" >> LC.html
echo "</select>" >> ST.html
echo "</select>" >> SG.html
echo "</select>" >> SI.html
echo "</select>" >> SX.html
echo "</select>" >> KN.html
echo "</select>" >> VC.html
echo "</select>" >> TH.html
echo "</select>" >> TT.html
echo "</select>" >> TR.html
echo "</select>" >> UM.html
echo "</select>" >> AE.html
echo "</select>" >> VI.html

